name: CI/CD Deploy to Azure App Service (Docker)

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: real-time-betting-api
  AZURE_ACR_NAME: acrbettingapi27742
  ACR_LOGIN_SERVER: acrbettingapi27742.azurecr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $ACR_LOGIN_SERVER/betting-api:latest .

      - name: Push Docker image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/betting-api:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.ACR_LOGIN_SERVER }}/betting-api:latest
